name: Node CI
on:
  - push
  - pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NAME: auto-globals
    strategy:
      matrix:
        node-version:
          - 16.x
          - 18.x
          - 19.x
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install
        run: npm i
      - name: Install Redrun
        run: npm i redrun -g
      - name: Lint
        run: redrun fix:lint
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Typos Install
        run: which typos || cargo install typos-cli
      - name: Typos
        run: typos --write-changes
      - name: Commit fixes
        uses: EndBug/add-and-commit@v9
        with:
          message: "chore: ${{ env.NAME }}: lint: actions ☘️ "
      - name: Coverage
        run: redrun coverage:ci report
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: typos-action
        uses: crate-ci/typos@v1.0.4
